# Generated by Django 5.1.4 on 2024-12-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='prepod_photos/'),
        ),
    ]
