# Generated by Django 5.1.4 on 2024-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prepod_bio_prepod_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionnaireItem',
        ),
    ]
