# Generated by Django 5.1.4 on 2024-12-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_question_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='QuestionCategory',
        ),
    ]
